INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (1, 'Planter, entretenir des arbres', 'INTERETS - ACTIVITES', 1, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (2, 'Effectuer des réparations électriques ou électroniques', 'INTERETS - ACTIVITES', 1, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (3, 'Faire de la couture', 'INTERETS - ACTIVITES', 1, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (4, 'Réparer des automobiles', 'INTERETS - ACTIVITES', 1, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (5, 'Fabriquer des objets avec du bois', 'INTERETS - ACTIVITES', 1, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (6, 'Conduire un camion ou un tracteur', 'INTERETS - ACTIVITES', 1, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (7, 'Faire des déménagements', 'INTERETS - ACTIVITES', 1, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (8, 'Entretenir ou réparer de la plomberie ou des systèmes de ventilation', 'INTERETS - ACTIVITES', 1, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (9, 'Travailler avec des animaux et en prendre soin', 'INTERETS - ACTIVITES', 1, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (10, 'Travailler à l''extérieur (exposé/e à la pluie, au soleil)', 'INTERETS - ACTIVITES', 1, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (11, 'Travailler avec de la machinerie', 'INTERETS - ACTIVITES', 1, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (12, 'Préparer des repas, des banquets', 'INTERETS - ACTIVITES', 1, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (13, 'Travailler avec des outils tels que tournevis, ciseaux', 'INTERETS - ACTIVITES', 1, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (14, 'Effectuer des travaux de peinture', 'INTERETS - ACTIVITES', 1, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (15, 'Suivre un cours de dessin mécanique', 'INTERETS - ACTIVITES', 1, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (16, 'Lire des revues scientifiques ou spécialisées', 'INTERETS - ACTIVITES', 2, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (17, 'Faire des expériences sur le comportement des animaux', 'INTERETS - ACTIVITES', 2, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (18, 'Effectuer des analyses de laboratoire', 'INTERETS - ACTIVITES', 2, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (19, 'Suivre des cours de sciences', 'INTERETS - ACTIVITES', 2, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (20, 'Etablir un diagnostic de maladie chez des patients', 'INTERETS - ACTIVITES', 2, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (21, 'Expérimenter de nouvelles cultures végétales', 'INTERETS - ACTIVITES', 2, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (22, 'Créer une nouvelle source d''énergie', 'INTERETS - ACTIVITES', 2, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (23, 'Concevoir un barrage électrique, un pont', 'INTERETS - ACTIVITES', 2, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (24, 'Résoudre des problèmes mathématiques', 'INTERETS - ACTIVITES', 2, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (25, 'Faire des recherches scientifiques pour satisfaire ma curiosité', 'INTERETS - ACTIVITES', 2, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (26, 'Produire un rapport sur l''évolution économique d''une région', 'INTERETS - ACTIVITES', 2, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (27, 'Concevoir un plan de reboisement', 'INTERETS - ACTIVITES', 2, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (28, 'Planifier des soins ou des traitements à donner à des patients', 'INTERETS - ACTIVITES', 2, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (29, 'Faire des recherches sur les civilisations anciennes', 'INTERETS - ACTIVITES', 2, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (30, 'Faire de la programmation informatique', 'INTERETS - ACTIVITES', 2, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (31, 'Ecrire des romans, des articles de journaux', 'INTERETS - ACTIVITES', 3, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (32, 'Dessiner des meubles, des plans de maison', 'INTERETS - ACTIVITES', 3, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (33, 'Interpréter ou mettre en scène une pièce de théâtre', 'INTERETS - ACTIVITES', 3, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (34, 'Jouer dans un orchestre', 'INTERETS - ACTIVITES', 3, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (35, 'Créer des pièces d''artisanat', 'INTERETS - ACTIVITES', 3, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (36, 'Imaginer de nouvelles façons de faire les choses', 'INTERETS - ACTIVITES', 3, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (37, 'Embellir l''environnement', 'INTERETS - ACTIVITES', 3, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (38, 'Créer une nouvelle coupe de cheveux ou de nouveaux vêtements', 'INTERETS - ACTIVITES', 3, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (39, 'Faire de la photographie publicitaire ou artistique', 'INTERETS - ACTIVITES', 3, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (40, 'Concevoir et réaliser des arrangements de fleurs', 'INTERETS - ACTIVITES', 3, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (41, 'Imaginer une bande dessinée', 'INTERETS - ACTIVITES', 3, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (42, 'Peindre des tableaux pour une exposition', 'INTERETS - ACTIVITES', 3, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (43, 'Décorer des vitrines de magasins', 'INTERETS - ACTIVITES', 3, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (44, 'Ecrire des critiques de pièces de théâtre, de films', 'INTERETS - ACTIVITES', 3, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (45, 'Apprendre des langues', 'INTERETS - ACTIVITES', 3, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (46, 'S''engager dans des organismes sociaux ou communautaires', 'INTERETS - ACTIVITES', 4, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (47, 'Rencontrer des gens pour les aider à résoudre leurs problèmes personnels', 'INTERETS - ACTIVITES', 4, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (48, 'Travailler dans une garderie d''enfants', 'INTERETS - ACTIVITES', 4, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (49, 'Enseigner aux enfants, à des adolescents', 'INTERETS - ACTIVITES', 4, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (50, 'Aider les gens à prendre conscience de leurs possibilités', 'INTERETS - ACTIVITES', 4, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (51, 'Animer un groupe', 'INTERETS - ACTIVITES', 4, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (52, 'Agir comme hôte/hôtesse lors d''un congrés', 'INTERETS - ACTIVITES', 4, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (53, 'Tenir un kiosque d''information', 'INTERETS - ACTIVITES', 4, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (54, 'Offrir un service d''aide téléphonique', 'INTERETS - ACTIVITES', 4, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (55, 'Consulter les gens sur leurs besoins (sondage, enquête...)', 'INTERETS - ACTIVITES', 4, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (56, 'S''occuper des personnes handicapées physiquement', 'INTERETS - ACTIVITES', 4, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (57, 'Soigner un malade', 'INTERETS - ACTIVITES', 4, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (58, 'Aider les délinquants à se réhabiliter', 'INTERETS - ACTIVITES', 4, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (59, 'Organiser des loisirs', 'INTERETS - ACTIVITES', 4, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (60, 'Echanger des idées avec d''autres personnes', 'INTERETS - ACTIVITES', 4, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (61, 'Vendre un produit ou une idée', 'INTERETS - ACTIVITES', 5, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (62, 'Mettre sur pied son propre commerce', 'INTERETS - ACTIVITES', 5, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (63, 'Donner des conférences', 'INTERETS - ACTIVITES', 5, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (64, 'Acheter pour le compte d''un grand magasin', 'INTERETS - ACTIVITES', 5, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (65, 'Marchander', 'INTERETS - ACTIVITES', 5, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (66, 'Diriger du personnel', 'INTERETS - ACTIVITES', 5, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (67, 'Défendre une cause', 'INTERETS - ACTIVITES', 5, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (68, 'Faire de la sélection de candidats', 'INTERETS - ACTIVITES', 5, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (69, 'S''engager à fond dans des activités sociales dans son travail ou dans son quartier', 'INTERETS - ACTIVITES', 5, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (70, 'Diriger une entreprise financière', 'INTERETS - ACTIVITES', 5, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (71, 'Lancer un nouveau produit', 'INTERETS - ACTIVITES', 5, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (72, 'Fonder un club de consommateurs, une association de protection de l''environnement', 'INTERETS - ACTIVITES', 5, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (73, 'Gérer un projet spécial', 'INTERETS - ACTIVITES', 5, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (74, 'Faire de la politique (municipal, départemental…)', 'INTERETS - ACTIVITES', 5, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (75, 'Lancer un concours de promotion, une campagne de publicité', 'INTERETS - ACTIVITES', 5, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (76, 'Etablir des comptes-rendus des dépenses', 'INTERETS - ACTIVITES', 6, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (77, 'Préparer des procès-verbaux de réunion', 'INTERETS - ACTIVITES', 6, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (78, 'Tenir une caisse dans un établissement commercial ou financier', 'INTERETS - ACTIVITES', 6, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (79, 'Faire un inventaire et passer des commandes', 'INTERETS - ACTIVITES', 6, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (80, 'Manipuler un appareil à traitement de textes', 'INTERETS - ACTIVITES', 6, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (81, 'Maintenir un système de classement (archives, bibliothèque)', 'INTERETS - ACTIVITES', 6, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (82, 'Garder mon espace de travail en ordre', 'INTERETS - ACTIVITES', 6, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (83, 'Faire des opérations mathématiques pour préparer des rapports ou faire la tenue de livres', 'INTERETS - ACTIVITES', 6, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (84, 'S''adonner à des activités régulières', 'INTERETS - ACTIVITES', 6, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (85, 'Classer des lettres, des rapports', 'INTERETS - ACTIVITES', 6, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (86, 'Recevoir et émettre des appels téléphoniques', 'INTERETS - ACTIVITES', 6, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (87, 'Vérifer des rapports financiers', 'INTERETS - ACTIVITES', 6, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (88, 'Faire fonctionner toutes sortes de machines de bureau', 'INTERETS - ACTIVITES', 6, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (89, 'Effectuer des tâches clairement définies', 'INTERETS - ACTIVITES', 6, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (90, 'Dactylographier ou réviser des lettres ou des rapports', 'INTERETS - ACTIVITES', 6, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (91, 'Mécanicien/mécanicienne auto', 'INTERET - METIERS', 1, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (92, 'Eleveur/éleveuse de bétails', 'INTERET - METIERS', 1, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (93, 'Technicien/technicienne dentaire', 'INTERET - METIERS', 1, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (94, 'Travailleur/travailleuse de la construction (menuiserie)', 'INTERET - METIERS', 1, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (95, 'Couturier/couturière en usine', 'INTERET - METIERS', 1, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (96, 'Technicien/technicienne en aménagement de la faune', 'INTERET - METIERS', 1, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (97, 'Horlager/horlogère', 'INTERET - METIERS', 1, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (98, 'Technicien/technicienne du meuble et du bois ouvré (ébeniste)', 'INTERET - METIERS', 1, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (99, 'Plombier/plombière', 'INTERET - METIERS', 1, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (100, 'Technicien/technicienne en mécanique du bâtiment', 'INTERET - METIERS', 1, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (101, 'Conducteur/conductrice d''autobus', 'INTERET - METIERS', 1, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (102, 'Technicien/technicienne en entretien d''aéronefs (aéronautique)', 'INTERET - METIERS', 1, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (103, 'Réparteur/réparatrice de télévision', 'INTERET - METIERS', 1, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (104, 'Ingénieur/ingénieure civil', 'INTERET - METIERS', 1, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (105, 'Cuisinier/cuisinière', 'INTERET - METIERS', 1, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (106, 'Ingénieur/ingénieure en chimie, physique', 'INTERET - METIERS', 2, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (107, 'Technicien/technicienne en laboratoire médical', 'INTERET - METIERS', 2, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (108, 'Chercheur /chercheuse scientifique', 'INTERET - METIERS', 2, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (109, 'Technicien/technicienne en radiologie (rayon X)', 'INTERET - METIERS', 2, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (110, 'Biologiste', 'INTERET - METIERS', 2, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (111, 'Technicien/ technicienne en informatique', 'INTERET - METIERS', 2, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (112, 'Médecin ou vétérinaire', 'INTERET - METIERS', 2, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (113, 'Technicien/technicienne en transformation des produits forestiers', 'INTERET - METIERS', 2, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (114, 'Météorologiste', 'INTERET - METIERS', 2, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (115, 'Astronome (étudier le mouvement des astres dans le ciel)', 'INTERET - METIERS', 2, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (116, 'Technicien/technicienne en dessin conception mécanique', 'INTERET - METIERS', 2, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (117, 'Economiste', 'INTERET - METIERS', 2, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (118, 'Technicien/technicienne en procédés métallurgiques (spécialistes dans la transformation des métaux)', 'INTERET - METIERS', 2, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (119, 'Botaniste', 'INTERET - METIERS', 2, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (120, 'Technicien/technicienne en chimie analytique (analyse de nouveaux produits chimiques)', 'INTERET - METIERS', 2, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (121, 'Musicien/musicienne', 'INTERET - METIERS', 3, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (122, 'Ecrivain/écrivaine', 'INTERET - METIERS', 3, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (123, 'Fleuriste', 'INTERET - METIERS', 3, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (124, 'Journaliste', 'INTERET - METIERS', 3, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (125, 'Décorateur/décoratrice d''intérieur', 'INTERET - METIERS', 3, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (126, 'Compositeur/compositrice (musique)', 'INTERET - METIERS', 3, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (127, 'Mannequin', 'INTERET - METIERS', 3, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (128, 'Photographe', 'INTERET - METIERS', 3, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (129, 'Graphiste', 'INTERET - METIERS', 3, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (130, 'Directeur / directrice de publicité', 'INTERET - METIERS', 3, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (131, 'Architecte', 'INTERET - METIERS', 3, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (132, 'Interprète', 'INTERET - METIERS', 3, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (133, 'Chanteur/chanteuse', 'INTERET - METIERS', 3, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (134, 'Comédien/comédienne', 'INTERET - METIERS', 3, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (135, 'Professeur de dessin', 'INTERET - METIERS', 3, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (136, 'Infirmier/infirmière auxiliaire', 'INTERET - METIERS', 4, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (137, 'Agent/agente à l''aide sociale', 'INTERET - METIERS', 4, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (138, 'Travailleur/travailleuse sociale', 'INTERET - METIERS', 4, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (139, 'Barman/barmaid', 'INTERET - METIERS', 4, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (140, 'Professeur des écoles', 'INTERET - METIERS', 4, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (141, 'Technicien/technicienne en loisirs', 'INTERET - METIERS', 4, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (142, 'Technicien/technicienne en garderie d''enfants', 'INTERET - METIERS', 4, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (143, 'Orthophoniste - logopède', 'INTERET - METIERS', 4, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (144, 'Esthéticien/esthéticienne', 'INTERET - METIERS', 4, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (145, 'Technicien/technicienne policier/policière', 'INTERET - METIERS', 4, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (146, 'Médecin généraliste (de famille)', 'INTERET - METIERS', 4, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (147, 'Directeur/directrice du personnel', 'INTERET - METIERS', 4, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (148, 'Bibliothécaire', 'INTERET - METIERS', 4, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (149, 'Technicien/technicienne en hygiène dentaire', 'INTERET - METIERS', 4, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (150, 'Technicien/technicienne en réadaptation physique', 'INTERET - METIERS', 4, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (151, 'Agent/agente de publicité (marketing)', 'INTERET - METIERS', 5, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (152, 'Avocat/avocate', 'INTERET - METIERS', 5, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (153, 'Agent/agente de bord', 'INTERET - METIERS', 5, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (154, 'Chef de rayons de supermarché', 'INTERET - METIERS', 5, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (155, 'Commis-vendeur/vendeuse', 'INTERET - METIERS', 5, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (156, 'Directeur/directrice d''une entreprise', 'INTERET - METIERS', 5, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (157, 'Politicien/politicienne', 'INTERET - METIERS', 5, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (158, 'Directeur/directrice des ventes', 'INTERET - METIERS', 5, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (159, 'Vendeur/vendeuse en assurances', 'INTERET - METIERS', 5, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (160, 'Gérant/gérante d''hôtel', 'INTERET - METIERS', 5, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (161, 'Technicien/technicienne de tourisme', 'INTERET - METIERS', 5, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (162, 'Patron d''un commerce (propriétaire)', 'INTERET - METIERS', 5, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (163, 'Courtier/courtière en immeuble', 'INTERET - METIERS', 5, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (164, 'Acheteur/acheteuse', 'INTERET - METIERS', 5, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (165, 'Agent/agente de voyage', 'INTERET - METIERS', 5, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (166, 'Aide-comptable', 'INTERET - METIERS', 6, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (167, 'Technicien/technicienne en finance (comptablitité)', 'INTERET - METIERS', 6, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (168, 'Opérateur/opératrice en informatique', 'INTERET - METIERS', 6, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (169, 'Secrétaire de service juridique, médical', 'INTERET - METIERS', 6, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (170, 'Archiviste médical', 'INTERET - METIERS', 6, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (171, 'Commis aux renseignements', 'INTERET - METIERS', 6, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (172, 'Bibliotechnicien/bibliotechnicienne', 'INTERET - METIERS', 6, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (173, 'Expert/experte en impôt', 'INTERET - METIERS', 6, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (174, 'Caissier/caissière de banque', 'INTERET - METIERS', 6, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (175, 'Réceptionniste', 'INTERET - METIERS', 6, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (176, 'Commis au service de la paie', 'INTERET - METIERS', 6, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (177, 'Gérant/gérante du service de crédits', 'INTERET - METIERS', 6, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (178, 'Commis de bureau', 'INTERET - METIERS', 6, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (179, 'Sténo-dactylo', 'INTERET - METIERS', 6, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (180, 'Technicien/technicienne judiciaire (aux greffes)', 'INTERET - METIERS', 6, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (181, 'Ma capacité à soulever des poids lourds de (3 à 11 kg) est :', 'APTITUDES', 1, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (182, 'Ma capacité à utiliser des outils, des objets', 'APTITUDES', 1, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (183, 'Mon habilité à conduire un gros véhicule (camion, autobus) est :', 'APTITUDES', 1, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (184, 'Mon aptitude à lire des plans est :', 'APTITUDES', 1, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (185, 'Mon habilité dans les mouvements demandant : à voir et à manipuler en même temps est :', 'APTITUDES', 1, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (186, 'Ma capacité à comprendre le fonctionnement des éléments de base de tout ouvrage mécanique, électrique (turbine)', 'APTITUDES', 1, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (187, 'La rapidité de mes réflexes est :', 'APTITUDES', 1, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (188, 'Mon habilité à faire des réparations est :', 'APTITUDES', 1, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (189, 'Ma capacité à m''occuper d''élevage d''animaux est :', 'APTITUDES', 1, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (190, 'Ma capacité à installer et à manipuler divers outils,  machines ou appareils est :', 'APTITUDES', 1, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (191, 'Mes aptitudes en mathématiques sont :', 'APTITUDES', 2, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (192, 'Mes capacités en sciences (biologie, physique)', 'APTITUDES', 2, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (193, 'Ma capacité à me concentrer sur une tâche abstraite est :', 'APTITUDES', 2, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (194, 'Ma capacité d''analyse est :', 'APTITUDES', 2, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (195, 'Ma capacité de synthèse est :', 'APTITUDES', 2, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (196, 'Mon talent à rédiger clairement un texte est :', 'APTITUDES', 2, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (197, 'Ma capacité à saisir et comprendre des directives rapidement est :', 'APTITUDES', 2, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (198, 'Mon habileté à apprendre des nouveaux sujets avec facilité et avec aisance est :', 'APTITUDES', 2, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (199, 'Mon habileté à solutionner des problèmes abstraits est :', 'APTITUDES', 2, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (200, 'Mon habileté à faire des travaux de laboratoire est :', 'APTITUDES', 2, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (201, 'Ma capacité à me représenter la forme d''objets en deux ou trois dimensions est :', 'APTITUDES', 3, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (202, 'Ma capacité à apprendre des langues, y compris ma langue maternelle est :', 'APTITUDES', 3, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (203, 'Mon aptitude dans les arts plastiques (dessin, sculpture)', 'APTITUDES', 3, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (204, 'Mon aptitude dans les arts de la scène (théâtre, danse)', 'APTITUDES', 3, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (205, 'Ma capacité d''inventer, de créer', 'APTITUDES', 3, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (206, 'Ma capacité  à accepter la critique est :', 'APTITUDES', 3, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (207, 'Ma capacité à travailler par moi-même est :', 'APTITUDES', 3, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (208, 'Mon aptitude à exprimer concrètement mes idées créatrices dans le domaine de mon choix (musique, écriture)', 'APTITUDES', 3, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (209, 'Mon aptitude à tolérer l''insécurité (peur du lendemain) est :', 'APTITUDES', 3, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (210, 'Mon habileté à observer les légères diffèrences de formes ou de teintes est :', 'APTITUDES', 3, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (211, 'Mon aptitude à travailler en équipe est :', 'APTITUDES', 4, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (212, 'Mon sens de l''organisation est :', 'APTITUDES', 4, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (213, 'Ma faculté de prévoir, de deviner (intuition) est :', 'APTITUDES', 4, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (214, 'Ma capacité à diriger des interactions dans un groupe (animation) est :', 'APTITUDES', 4, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (215, 'Ma capacité de maintenir des relations suivies avec les gens est :', 'APTITUDES', 4, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (216, 'Ma capacité à être touché/e par les émotions des autres tout en demeurant objectif (empathie) est :', 'APTITUDES', 4, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (217, 'Ma capacité à réagir correctement devant les situations qui se présentent (équilibre émotionnel) est :', 'APTITUDES', 4, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (218, 'Ma capacité à aider les autres, à les comprendre', 'APTITUDES', 4, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (219, 'Ma capacité à expliquer les choses clairement est :', 'APTITUDES', 4, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (220, 'Ma capacité à communiquer avec les autres est :', 'APTITUDES', 4, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (221, 'Ma capacité à m''exprimer en public est :', 'APTITUDES', 5, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (222, 'Mon talent pour vendre est :', 'APTITUDES', 5, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (223, 'Mon sens des affaires est :', 'APTITUDES', 5, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (224, 'Mon habileté à diriger, à mener les autres est :', 'APTITUDES', 5, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (225, 'Ma capacité à prendre une décision seul/e est :', 'APTITUDES', 5, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (226, 'Mon habileté à me faire valoir en société est :', 'APTITUDES', 5, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (227, 'Mon aptitude à défendre une cause est :', 'APTITUDES', 5, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (228, 'Ma capacité à être le/la premier/ère à proposer ou à faire quelque chose est :', 'APTITUDES', 5, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (229, 'Mon talent pour persuader les gens est :', 'APTITUDES', 5, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (230, 'Ma capacité à demeurer enthousiaste et énergique même en situation difficile est :', 'APTITUDES', 5, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (231, 'Ma capacité à me conformer aux règles établies est :', 'APTITUDES', 6, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (232, 'Mon aptitude à travailler avec précision est :', 'APTITUDES', 6, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (233, 'Ma capacité à disposer les choses selon le rang, la place qui leur convient est :', 'APTITUDES', 6, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (234, 'Mon aptitude en français est :', 'APTITUDES', 6, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (235, 'Mon aptitude à travailler avec les chiffres est :', 'APTITUDES', 6, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (236, 'Mon aptitude à observer les détails est : ', 'APTITUDES', 6, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (237, 'Ma capacité à m''adapter à un travail routinier est :', 'APTITUDES', 6, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (238, 'Ma capacité à tenir des dossiers et des registres à jour est :', 'APTITUDES', 6, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (239, 'Ma capacité à comprendre et à exécuter des instructions est :', 'APTITUDES', 6, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (240, 'Mon aptitude à comprendre les structures administratives est :', 'APTITUDES', 6, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (241, 'Je suis conformiste, je me plie facilement aux réglements du milieu où je vis', 'PERSONNALITE', 1, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (242, 'Généralement, j''évite de me faire remarquer', 'PERSONNALITE', 1, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (243, 'J''aime les choses matérielles, concrètes', 'PERSONNALITE', 1, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (244, 'Dans mon travail ou autre, je me montre persistant/e.', 'PERSONNALITE', 1, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (245, 'Je démontre un esprit d''équipe pratique et je préfère agir plutôt que parler', 'PERSONNALITE', 1, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (246, 'Je suis d''un naturel réservé; pour savoir mon opinion, on doit me le demander', 'PERSONNALITE', 1, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (247, 'Je suis porté/e à faire le ménage et à prendre soin de mes biens.', 'PERSONNALITE', 1, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (248, 'Je suis stable dans mes opinions, ma façon de vivre', 'PERSONNALITE', 1, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (249, 'Je me présente toujours au naturel, tel/le que je suis.', 'PERSONNALITE', 1, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (250, 'Avec mon propre entourage, je suis franc/he et sincère.', 'PERSONNALITE', 1, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (251, 'J''analyse les idées, les événements', 'PERSONNALITE', 2, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (252, 'J''ai l''esprit critique et n''accepte pas facilement n''importe qu''elle idée. ', 'PERSONNALITE', 2, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (253, 'Je suis d''un naturel très curieux sur à peu près tout.', 'PERSONNALITE', 2, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (254, 'Je tiens à mon indépendance sur le plan des idées, du travail', 'PERSONNALITE', 2, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (255, 'Les gens me considèrent comme une personne intellectuelle plutôt qu''émotive', 'PERSONNALITE', 2, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (256, 'J''ai l''esprit inventif : il m''arrive souvent de trouver une solution originale et efficace à un problème', 'PERSONNALITE', 2, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (257, 'Dans mes activités scolaires ou autres, je me montre méthodique et rationnel/le', 'PERSONNALITE', 2, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (258, 'J''aime la précision dans tout ce que je fais', 'PERSONNALITE', 2, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (259, 'Je demeure réservé/e dans l''expression de mes opinions, de mes sentiments et de mes actes', 'PERSONNALITE', 2, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (260, 'Avant toute décision, je réunis le maximum d''informations possible.', 'PERSONNALITE', 2, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (261, 'Mes amis me considèrent compliquée/e.', 'PERSONNALITE', 3, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (262, 'Dans mes diverses activités, je manque souvent d''ordre.', 'PERSONNALITE', 3, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (263, 'Dans mes travaux, je fais preuve d''originalité', 'PERSONNALITE', 3, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (264, 'Je suis d''un caractère impulsif.', 'PERSONNALITE', 3, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (265, 'Mes émotions sont généralement intenses.', 'PERSONNALITE', 3, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (266, 'Je suis porté/e à tout idéaliser et à chercher la perfection.', 'PERSONNALITE', 3, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (267, 'J''agis et je pense souvent de façon non conformiste, c''est-à-dire diffèremment des autres.', 'PERSONNALITE', 3, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (268, 'J''exprime mes sentiments par l''entremise de la musique, des beaux arts', 'PERSONNALITE', 3, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (269, 'Les lendemains ne m''inquiètent pas : je vis au jour le jour.', 'PERSONNALITE', 3, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (270, 'J''ai besoin de beaucoup de liberté dans tout ce que j''entreprends.', 'PERSONNALITE', 3, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (271, 'Quand un problème se pose, je préfère le régler par la discussion et l''entente avec les gens qui m''entourent', 'PERSONNALITE', 4, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (272, 'Je sais me montrer souple, conciliant/e.', 'PERSONNALITE', 4, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (273, 'Mes  amis/es me considèrent comme bienveillant/e et compréhensif/ve.', 'PERSONNALITE', 4, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (274, 'Généralement, les gens peuvent compter sur ma coopération.', 'PERSONNALITE', 4, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (275, 'Les gens me qualifient de sociale et sympathique.', 'PERSONNALITE', 4, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (276, 'Je suis d''un naturel serviable.', 'PERSONNALITE', 4, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (277, 'J''accepte et j''assume des responsabilités.', 'PERSONNALITE', 4, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (278, 'On me consièdère généreux/se.', 'PERSONNALITE', 4, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (279, 'Dans la majorité des circonstances, je suis perspicace', 'PERSONNALITE', 4, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (280, 'Dans l''action comme dans la façon de m''exprimer, je montre de la délicatesse.', 'PERSONNALITE', 4, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (281, 'L''ambition ne m''effraye pas.', 'PERSONNALITE', 5, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (282, 'Je suis un/e optimiste né/e.', 'PERSONNALITE', 5, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (283, 'Je suis sociable et populaire ; je parle à tout le monde', 'PERSONNALITE', 5, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (284, 'Je défends toujours mes opinions', 'PERSONNALITE', 5, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (285, 'Il m''arrive souvent de me montrer autoritaire.', 'PERSONNALITE', 5, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (286, 'L''aventure m''attire beaucoup.', 'PERSONNALITE', 5, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (287, 'Généralement, je suis sûr/e de moi.', 'PERSONNALITE', 5, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (288, 'Mes impulsions me dictent souvent ma conduite.', 'PERSONNALITE', 5, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (289, 'J''aime être responsable d''activités.', 'PERSONNALITE', 5, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (290, 'Même dans des situations critiques ou tendues, je sais prendre l''initiative nécessaire.', 'PERSONNALITE', 5, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (291, 'Je suis maître de moi, d''un calme exemplaire.', 'PERSONNALITE', 6, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (292, 'J''obéis facilement aux règlements et aux ordres.', 'PERSONNALITE', 6, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (293, 'Dans mes travaux, je suis persistant/e et consciencieux/se.', 'PERSONNALITE', 6, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (294, 'Je m''efforce de me montrer compétent/e dans ce qu''on exige de moi.', 'PERSONNALITE', 6, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (295, 'L''esprit concret et pratique me guide .', 'PERSONNALITE', 6, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (296, 'J''agis méthodiquement dans tout ce que je fais.', 'PERSONNALITE', 6, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (297, 'Je travaille avec beaucoup de soin.', 'PERSONNALITE', 6, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (298, 'D''une journée à l''autre, j''aime exécuter des tâches semblables.', 'PERSONNALITE', 6, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (299, 'Je suis timide et je préfère garder pour moi mes sentiments, mes émotions et mes idées.', 'PERSONNALITE', 6, null);
INSERT INTO `holland-back`.question (id, text, category, serial, img) VALUES (300, 'J''aime recevoir des instructions bien claires qui me permettent de savoir exactement ce qu''on attend de moi.', 'PERSONNALITE', 6, null);
