INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (1, '01. Planter, entretenir des arbres', 'INTERETS - ACTIVITES', 1);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (2, '02. Effectuer des réparations électriques ou électroniques', 'INTERETS - ACTIVITES', 1);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (3, '03. Faire de la couture', 'INTERETS - ACTIVITES', 1);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (4, '04. Réparer des automobiles', 'INTERETS - ACTIVITES', 1);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (5, '05. Fabriquer des objets avec du bois', 'INTERETS - ACTIVITES', 1);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (6, '06. Conduire un camion ou un tracteur', 'INTERETS - ACTIVITES', 1);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (7, '07. Faire des déménagements', 'INTERETS - ACTIVITES', 1);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (8, '08. Entretenir ou réparer de la plomberie ou des systèmes de ventilation', 'INTERETS - ACTIVITES', 1);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (9, '09. Travailler avec des animaux et en prendre soin', 'INTERETS - ACTIVITES', 1);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (10, '10. Travailler à l''extérieur (exposé/e à la pluie, au soleil)', 'INTERETS - ACTIVITES', 1);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (11, '11. Travailler avec de la machinerie', 'INTERETS - ACTIVITES', 1);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (12, '12. Préparer des repas, des banquets', 'INTERETS - ACTIVITES', 1);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (13, '13. Travailler avec des outils tels que tournevis, ciseaux', 'INTERETS - ACTIVITES', 1);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (14, '14. Effectuer des travaux de peinture', 'INTERETS - ACTIVITES', 1);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (15, '15. Suivre un cours de dessin mécanique', 'INTERETS - ACTIVITES', 1);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (16, '01. Lire des revues scientifiques ou spécialisées', 'INTERETS - ACTIVITES', 2);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (17, '02. Faire des expériences sur le comportement des animaux', 'INTERETS - ACTIVITES', 2);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (18, '03. Effectuer des analyses de laboratoire', 'INTERETS - ACTIVITES', 2);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (19, '04. Suivre des cours de sciences', 'INTERETS - ACTIVITES', 2);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (20, '05. Etablir un diagnostic de maladie chez des patients', 'INTERETS - ACTIVITES', 2);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (21, '06. Expérimenter de nouvelles cultures végétales', 'INTERETS - ACTIVITES', 2);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (22, '07. Créer une nouvelle source d''énergie', 'INTERETS - ACTIVITES', 2);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (23, '08. Concevoir un barrage électrique, un pont', 'INTERETS - ACTIVITES', 2);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (24, '09. Résoudre des problèmes mathématiques', 'INTERETS - ACTIVITES', 2);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (25, '10. Faire des recherches scientifiques pour satisfaire ma curiosité', 'INTERETS - ACTIVITES', 2);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (26, '11. Produire un rapport sur l''évolution économique d''une région', 'INTERETS - ACTIVITES', 2);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (27, '12. Concevoir un plan de reboisement', 'INTERETS - ACTIVITES', 2);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (28, '13. Planifier des soins ou des traitements à donner à des patients', 'INTERETS - ACTIVITES', 2);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (29, '14. Faire des recherches sur les civilisations anciennes', 'INTERETS - ACTIVITES', 2);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (30, '15. Faire de la programmation informatique', 'INTERETS - ACTIVITES', 2);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (31, '01. Ecrire des romans, des articles de journaux', 'INTERETS - ACTIVITES', 3);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (32, '02. Dessiner des meubles, des plans de maison', 'INTERETS - ACTIVITES', 3);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (33, '03. Interpréter ou mettre en scène une pièce de théâtre', 'INTERETS - ACTIVITES', 3);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (34, '04. Jouer dans un orchestre', 'INTERETS - ACTIVITES', 3);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (35, '05. Créer des pièces d''artisanat', 'INTERETS - ACTIVITES', 3);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (36, '06. Imaginer de nouvelles façons de faire les choses', 'INTERETS - ACTIVITES', 3);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (37, '07. Embellir l''environnement', 'INTERETS - ACTIVITES', 3);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (38, '08. Créer une nouvelle coupe de cheveux ou de nouveaux vêtements', 'INTERETS - ACTIVITES', 3);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (39, '09. Faire de la photographie publicitaire ou artistique', 'INTERETS - ACTIVITES', 3);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (40, '10. Concevoir et réaliser des arrangements de fleurs', 'INTERETS - ACTIVITES', 3);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (41, '11. Imaginer une bande dessinée', 'INTERETS - ACTIVITES', 3);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (42, '12. Peindre des tableaux pour une exposition', 'INTERETS - ACTIVITES', 3);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (43, '13. Décorer des vitrines de magasins', 'INTERETS - ACTIVITES', 3);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (44, '14. Ecrire des critiques de pièces de théâtre, de films', 'INTERETS - ACTIVITES', 3);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (45, '15. Apprendre des langues', 'INTERETS - ACTIVITES', 3);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (46, '01. S''engager dans des organismes sociaux ou communautaires', 'INTERETS - ACTIVITES', 4);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (47, '02. Rencontrer des gens pour les aider à résoudre leurs problèmes personnels', 'INTERETS - ACTIVITES', 4);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (48, '03. Travailler dans une garderie d''enfants', 'INTERETS - ACTIVITES', 4);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (49, '04. Enseigner aux enfants, à des adolescents', 'INTERETS - ACTIVITES', 4);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (50, '05. Aider les gens à prendre conscience de leurs possibilités', 'INTERETS - ACTIVITES', 4);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (51, '06. Animer un groupe', 'INTERETS - ACTIVITES', 4);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (52, '07. Agir comme hôte/hôtesse lors d''un congrés', 'INTERETS - ACTIVITES', 4);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (53, '08. Tenir un kiosque d''information', 'INTERETS - ACTIVITES', 4);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (54, '09. Offrir un service d''aide téléphonique', 'INTERETS - ACTIVITES', 4);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (55, '10. Consulter les gens sur leurs besoins (sondage, enquête...)', 'INTERETS - ACTIVITES', 4);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (56, '11. S''occuper des personnes handicapées physiquement', 'INTERETS - ACTIVITES', 4);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (57, '12. Soigner un malade', 'INTERETS - ACTIVITES', 4);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (58, '13. Aider les délinquants à se réhabiliter', 'INTERETS - ACTIVITES', 4);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (59, '14. Organiser des loisirs', 'INTERETS - ACTIVITES', 4);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (60, '15. Echanger des idées avec d''autres personnes', 'INTERETS - ACTIVITES', 4);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (61, '01. Vendre un produit ou une idée', 'INTERETS - ACTIVITES', 5);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (62, '02. Mettre sur pied son propre commerce', 'INTERETS - ACTIVITES', 5);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (63, '03. Donner des conférences', 'INTERETS - ACTIVITES', 5);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (64, '04. Acheter pour le compte d''un grand magasin', 'INTERETS - ACTIVITES', 5);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (65, '05. Marchander', 'INTERETS - ACTIVITES', 5);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (66, '06. Diriger du personnel', 'INTERETS - ACTIVITES', 5);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (67, '07. Défendre une cause', 'INTERETS - ACTIVITES', 5);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (68, '08. Faire de la sélection de candidats', 'INTERETS - ACTIVITES', 5);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (69, '09. S''engager à fond dans des activités sociales dans son travail ou dans son quartier', 'INTERETS - ACTIVITES', 5);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (70, '10. Diriger une entreprise financière', 'INTERETS - ACTIVITES', 5);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (71, '11. Lancer un nouveau produit', 'INTERETS - ACTIVITES', 5);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (72, '12. Fonder un club de consommateurs, une association de protection de l''environnement', 'INTERETS - ACTIVITES', 5);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (73, '13. Gérer un projet spécial', 'INTERETS - ACTIVITES', 5);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (74, '14. Faire de la politique (municipal, départemental…)', 'INTERETS - ACTIVITES', 5);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (75, '15. Lancer un concours de promotion, une campagne de publicité', 'INTERETS - ACTIVITES', 5);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (76, '01. Etablir des comptes-rendus des dépenses', 'INTERETS - ACTIVITES', 6);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (77, '02. Préparer des procès-verbaux de réunion', 'INTERETS - ACTIVITES', 6);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (78, '03. Tenir une caisse dans un établissement commercial ou financier', 'INTERETS - ACTIVITES', 6);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (79, '04. Faire un inventaire et passer des commandes', 'INTERETS - ACTIVITES', 6);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (80, '05. Manipuler un appareil à traitement de textes', 'INTERETS - ACTIVITES', 6);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (81, '06. Maintenir un système de classement (archives, bibliothèque)', 'INTERETS - ACTIVITES', 6);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (82, '07. Garder mon espace de travail en ordre', 'INTERETS - ACTIVITES', 6);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (83, '08. Faire des opérations mathématiques pour préparer des rapports ou faire la tenue de livres', 'INTERETS - ACTIVITES', 6);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (84, '09. S''adonner à des activités régulières', 'INTERETS - ACTIVITES', 6);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (85, '10. Classer des lettres, des rapports', 'INTERETS - ACTIVITES', 6);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (86, '11. Recevoir et émettre des appels téléphoniques', 'INTERETS - ACTIVITES', 6);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (87, '12. Vérifer des rapports financiers', 'INTERETS - ACTIVITES', 6);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (88, '13. Faire fonctionner toutes sortes de machines de bureau', 'INTERETS - ACTIVITES', 6);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (89, '14. Effectuer des tâches clairement définies', 'INTERETS - ACTIVITES', 6);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (90, '15. Dactylographier ou réviser des lettres ou des rapports', 'INTERETS - ACTIVITES', 6);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (91, '01. Mécanicien/mécanicienne auto', 'INTERET - METIERS', 1);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (92, '02. Eleveur/éleveuse de bétails', 'INTERET - METIERS', 1);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (93, '03. Technicien/technicienne dentaire', 'INTERET - METIERS', 1);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (94, '04. Travailleur/travailleuse de la construction (menuiserie)', 'INTERET - METIERS', 1);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (95, '05. Couturier/couturière en usine', 'INTERET - METIERS', 1);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (96, '06. Technicien/technicienne en aménagement de la faune', 'INTERET - METIERS', 1);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (97, '07. Horlager/horlogère', 'INTERET - METIERS', 1);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (98, '08. Technicien/technicienne du meuble et du bois ouvré (ébeniste)', 'INTERET - METIERS', 1);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (99, '09. Plombier/plombière', 'INTERET - METIERS', 1);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (100, '10. Technicien/technicienne en mécanique du bâtiment', 'INTERET - METIERS', 1);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (101, '11. Conducteur/conductrice d''autobus', 'INTERET - METIERS', 1);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (102, '12. Technicien/technicienne en entretien d''aéronefs (aéronautique)', 'INTERET - METIERS', 1);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (103, '13. Réparteur/réparatrice de télévision', 'INTERET - METIERS', 1);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (104, '14. Ingénieur/ingénieure civil', 'INTERET - METIERS', 1);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (105, '15. Cuisinier/cuisinière', 'INTERET - METIERS', 1);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (106, '01. Ingénieur/ingénieure en chimie, physique', 'INTERET - METIERS', 2);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (107, '02. Technicien/technicienne en laboratoire médical', 'INTERET - METIERS', 2);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (108, '03. Chercheur /chercheuse scientifique', 'INTERET - METIERS', 2);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (109, '04. Technicien/technicienne en radiologie (rayon X)', 'INTERET - METIERS', 2);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (110, '05. Biologiste', 'INTERET - METIERS', 2);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (111, '06. Technicien/ technicienne en informatique', 'INTERET - METIERS', 2);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (112, '07. Médecin ou vétérinaire', 'INTERET - METIERS', 2);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (113, '08. Technicien/technicienne en transformation des produits forestiers', 'INTERET - METIERS', 2);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (114, '09. Météorologiste', 'INTERET - METIERS', 2);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (115, '10. Astronome (étudier le mouvement des astres dans le ciel)', 'INTERET - METIERS', 2);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (116, '11. Technicien/technicienne en dessin conception mécanique', 'INTERET - METIERS', 2);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (117, '12. Economiste', 'INTERET - METIERS', 2);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (118, '13. Technicien/technicienne en procédés métallurgiques (spécialistes dans la transformation des métaux)', 'INTERET - METIERS', 2);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (119, '14. Botaniste', 'INTERET - METIERS', 2);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (120, '15. Technicien/technicienne en chimie analytique (analyse de nouveaux produits chimiques)', 'INTERET - METIERS', 2);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (121, '01. Musicien/musicienne', 'INTERET - METIERS', 3);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (122, '02. Ecrivain/écrivaine', 'INTERET - METIERS', 3);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (123, '03. Fleuriste', 'INTERET - METIERS', 3);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (124, '04. Journaliste', 'INTERET - METIERS', 3);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (125, '05. Décorateur/décoratrice d''intérieur', 'INTERET - METIERS', 3);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (126, '06. Compositeur/compositrice (musique)', 'INTERET - METIERS', 3);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (127, '07. Mannequin', 'INTERET - METIERS', 3);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (128, '08. Photographe', 'INTERET - METIERS', 3);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (129, '09. Graphiste', 'INTERET - METIERS', 3);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (130, '10. Directeur / directrice de publicité', 'INTERET - METIERS', 3);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (131, '11. Architecte', 'INTERET - METIERS', 3);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (132, '12. Interprète', 'INTERET - METIERS', 3);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (133, '13. Chanteur/chanteuse', 'INTERET - METIERS', 3);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (134, '14. comédien/comédienne', 'INTERET - METIERS', 3);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (135, '15. Professeur de dessin', 'INTERET - METIERS', 3);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (136, '01. Infirmier/infirmière auxiliaire', 'INTERET - METIERS', 4);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (137, '02. Agent/agente à l''aide sociale', 'INTERET - METIERS', 4);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (138, '03. Travailleur/travailleuse sociale', 'INTERET - METIERS', 4);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (139, '04. Barman/barmaid', 'INTERET - METIERS', 4);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (140, '05. Professeur des écoles', 'INTERET - METIERS', 4);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (141, '06. Technicien/technicienne en loisirs', 'INTERET - METIERS', 4);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (142, '07. Technicien/technicienne en garderie d''enfants', 'INTERET - METIERS', 4);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (143, '08. Orthophoniste - logopède', 'INTERET - METIERS', 4);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (144, '09. Esthéticien/esthéticienne', 'INTERET - METIERS', 4);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (145, '10. Technicien/technicienne policier/policière', 'INTERET - METIERS', 4);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (146, '11. Médecin généraliste (de famille)', 'INTERET - METIERS', 4);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (147, '12. Directeur/directrice du personnel', 'INTERET - METIERS', 4);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (148, '13. Bibliothécaire', 'INTERET - METIERS', 4);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (149, '14. Technicien/technicienne en hygiène dentaire', 'INTERET - METIERS', 4);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (150, '15. Technicien/technicienne en réadaptation physique', 'INTERET - METIERS', 4);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (151, '01. Agent/agente de publicité (marketing)', 'INTERET - METIERS', 5);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (152, '02. Avocat/avocate', 'INTERET - METIERS', 5);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (153, '03. Agent/agente de bord', 'INTERET - METIERS', 5);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (154, '04. Chef de rayons de supermarché', 'INTERET - METIERS', 5);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (155, '05. Commis-vendeur/vendeuse', 'INTERET - METIERS', 5);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (156, '06. Directeur/directrice d''une entreprise', 'INTERET - METIERS', 5);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (157, '07. Politicien/politicienne', 'INTERET - METIERS', 5);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (158, '08. Directeur/directrice des ventes', 'INTERET - METIERS', 5);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (159, '09. Vendeur/vendeuse en assurances', 'INTERET - METIERS', 5);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (160, '10. Gérant/gérante d''hôtel', 'INTERET - METIERS', 5);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (161, '11. Technicien/technicienne de tourisme', 'INTERET - METIERS', 5);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (162, '12. Patron d''un commerce (propriétaire)', 'INTERET - METIERS', 5);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (163, '13. Courtier/courtière en immeuble', 'INTERET - METIERS', 5);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (164, '14. Acheteur/acheteuse', 'INTERET - METIERS', 5);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (165, '15. Agent/agente de voyage', 'INTERET - METIERS', 5);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (166, '01. Aide-comptable', 'INTERET - METIERS', 6);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (167, '02. Technicien/technicienne en finance (comptablitité)', 'INTERET - METIERS', 6);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (168, '03. Opérateur/opératrice en informatique', 'INTERET - METIERS', 6);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (169, '04. Secrétaire de service juridique, médical', 'INTERET - METIERS', 6);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (170, '05. Archiviste médical', 'INTERET - METIERS', 6);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (171, '06. Commis aux renseignements', 'INTERET - METIERS', 6);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (172, '07. Bibliotechnicien/bibliotechnicienne', 'INTERET - METIERS', 6);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (173, '08. Expert/experte en impôt', 'INTERET - METIERS', 6);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (174, '09. Caissier/caissière de banque', 'INTERET - METIERS', 6);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (175, '10. Réceptionniste', 'INTERET - METIERS', 6);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (176, '11. Commis au service de la paie', 'INTERET - METIERS', 6);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (177, '12. Gérant/gérante du service de crédits', 'INTERET - METIERS', 6);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (178, '13. Commis de bureau', 'INTERET - METIERS', 6);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (179, '14. Sténo-dactylo', 'INTERET - METIERS', 6);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (180, '15. Technicien/technicienne judiciaire (aux greffes)', 'INTERET - METIERS', 6);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (181, '01. Ma capacité à soulever des poids lourds de (3 à 11 kg) est :', 'APTITUDES', 1);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (182, '02. Ma capacité à utiliser des outils, des objets', 'APTITUDES', 1);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (183, '03. Mon habilité à conduire un gros véhicule (camion, autobus) est :', 'APTITUDES', 1);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (184, '04. Mon aptitude à lire des plans est :', 'APTITUDES', 1);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (185, '05. Mon habilité dans les mouvements demandant : à voir et à manipuler en même temps est :', 'APTITUDES', 1);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (186, '06. Ma capacité à comprendre le fonctionnement des éléments de base de tout ouvrage mécanique, électrique (turbine)', 'APTITUDES', 1);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (187, '07. La rapidité de mes réflexes est :', 'APTITUDES', 1);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (188, '08. Mon habilité à faire des réparations est :', 'APTITUDES', 1);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (189, '09. Ma capacité à m''occuper d''élevage d''animaux est :', 'APTITUDES', 1);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (190, '10. Ma capacité à installer et à manipuler divers outils,  machines ou appareils est :', 'APTITUDES', 1);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (191, '01. Mes aptitudes en mathématiques sont :', 'APTITUDES', 2);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (192, '02. Mes capacités en sciences (biologie, physique)', 'APTITUDES', 2);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (193, '03. Ma capacité à me concentrer sur une tâche abstraite est :', 'APTITUDES', 2);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (194, '04. Ma capacité d''analyse est :', 'APTITUDES', 2);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (195, '05. Ma capacité de synthèse est :', 'APTITUDES', 2);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (196, '06. Mon talent à rédiger clairement un texte est :', 'APTITUDES', 2);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (197, '07. Ma capacité à saisir et comprendre des directives rapidement est :', 'APTITUDES', 2);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (198, '08. Mon habileté à apprendre des nouveaux sujets avec facilité et avec aisance est :', 'APTITUDES', 2);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (199, '09. Mon habileté à solutionner des problèmes abstraits est :', 'APTITUDES', 2);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (200, '10. Mon habileté à faire des travaux de laboratoire est :', 'APTITUDES', 2);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (201, '01. Ma capacité à me représenter la forme d''objets en deux ou trois dimensions est :', 'APTITUDES', 3);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (202, '02. Ma capacité à apprendre des langues, y compris ma langue maternelle est :', 'APTITUDES', 3);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (203, '03. Mon aptitude dans les arts plastiques (dessin, sculpture)', 'APTITUDES', 3);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (204, '04. Mon aptitude dans les arts de la scène (théâtre, danse)', 'APTITUDES', 3);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (205, '05. Ma capacité d''inventer, de créer', 'APTITUDES', 3);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (206, '06. Ma capacité  à accepter la critique est :', 'APTITUDES', 3);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (207, '07. Ma capacité à travailler par moi-même est :', 'APTITUDES', 3);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (208, '08. Mon aptitude à exprimer concrètement mes idées créatrices dans le domaine de mon choix (musique, écriture)', 'APTITUDES', 3);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (209, '09. Mon aptitude à tolérer l''insécurité (peur du lendemain) est :', 'APTITUDES', 3);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (210, '10. Mon habileté à observer les légères diffèrences de formes ou de teintes est :', 'APTITUDES', 3);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (211, '01. Mon aptitude à travailler en équipe est :', 'APTITUDES', 4);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (212, '02. Mon sens de l''organisation est :', 'APTITUDES', 4);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (213, '03. Ma faculté de prévoir, de deviner (intuition) est :', 'APTITUDES', 4);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (214, '04. Ma capacité à diriger des interactions dans un groupe (animation) est :', 'APTITUDES', 4);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (215, '05. Ma capacité de maintenir des relations suivies avec les gens est :', 'APTITUDES', 4);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (216, '06. Ma capacité à être touché/e par les émotions des autres tout en demeurant objectif (empathie) est :', 'APTITUDES', 4);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (217, '07. Ma capacité à réagir correctement devant les situations qui se présentent (équilibre émotionnel) est :', 'APTITUDES', 4);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (218, '08. Ma capacité à aider les autres, à les comprendre', 'APTITUDES', 4);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (219, '09. Ma capacité à expliquer les choses clairement est :', 'APTITUDES', 4);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (220, '10. Ma capacité à communiquer avec les autres est :', 'APTITUDES', 4);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (221, '01. Ma capacité à m''exprimer en public est :', 'APTITUDES', 5);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (222, '02. Mon talent pour vendre est :', 'APTITUDES', 5);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (223, '03. Mon sens des affaires est :', 'APTITUDES', 5);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (224, '04. Mon habileté à diriger, à mener les autres est :', 'APTITUDES', 5);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (225, '05. Ma capacité à prendre une décision seul/e est :', 'APTITUDES', 5);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (226, '06. Mon habileté à me faire valoir en société est :', 'APTITUDES', 5);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (227, '07. Mon aptitude à défendre une cause est :', 'APTITUDES', 5);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (228, '08. Ma capacité à être le/la premier/ère à proposer ou à faire quelque chose est :', 'APTITUDES', 5);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (229, '09. Mon talent pour persuader les gens est :', 'APTITUDES', 5);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (230, '10. Ma capacité à demeurer enthousiaste et énergique même en situation difficile est :', 'APTITUDES', 5);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (231, '01. Ma capacité à me conformer aux règles établies est :', 'APTITUDES', 6);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (232, '02. Mon aptitude à travailler avec précision est :', 'APTITUDES', 6);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (233, '03. Ma capacité à disposer les choses selon le rang, la place qui leur convient est :', 'APTITUDES', 6);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (234, '04. Mon aptitude en français est :', 'APTITUDES', 6);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (235, '05. Mon aptitude à travailler avec les chiffres est :', 'APTITUDES', 6);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (236, '06. Mon aptitude à observer les détails est : ', 'APTITUDES', 6);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (237, '07. Ma capacité à m''adapter à un travail routinier est :', 'APTITUDES', 6);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (238, '08. Ma capacité à tenir des dossiers et des registres à jour est :', 'APTITUDES', 6);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (239, '09. Ma capacité à comprendre et à exécuter des instructions est :', 'APTITUDES', 6);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (240, '10. Mon aptitude à comprendre les structures administratives est :', 'APTITUDES', 6);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (241, 'Je suis conformiste, je me plie facilement aux réglements du milieu où je vis', 'PERSONNALITE', 1);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (242, 'Généralement, j''évite de me faire remarquer', 'PERSONNALITE', 1);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (243, 'J''aime les choses matérielles, concrètes', 'PERSONNALITE', 1);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (244, 'Dans mon travail ou autre, je me montre persistant/e.', 'PERSONNALITE', 1);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (245, 'Je démontre un esprit d''équipe pratique et je préfère agir plutôt que parler', 'PERSONNALITE', 1);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (246, 'Je suis d''un naturel réservé; pour savoir mon opinion, on doit me le demander', 'PERSONNALITE', 1);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (247, 'Je suis porté/e à faire le ménage et à prendre soin de mes biens.', 'PERSONNALITE', 1);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (248, 'Je suis stable dans mes opinions, ma façon de vivre', 'PERSONNALITE', 1);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (249, 'Je me présente toujours au naturel, tel/le que je suis.', 'PERSONNALITE', 1);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (250, 'Avec mon propre entourage, je suis franc/he et sincère.', 'PERSONNALITE', 1);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (251, 'J''analyse les idées, les événements', 'PERSONNALITE', 2);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (252, 'J''ai l''esprit critique et n''accepte pas facilement n''importe qu''elle idée. ', 'PERSONNALITE', 2);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (253, 'Je suis d''un naturel très curieux sur à peu près tout.', 'PERSONNALITE', 2);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (254, 'Je tiens à mon indépendance sur le plan des idées, du travail', 'PERSONNALITE', 2);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (255, 'Les gens me considèrent comme une personne intellectuelle plutôt qu''émotive', 'PERSONNALITE', 2);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (256, 'J''ai l''esprit inventif : il m''arrive souvent de trouver une solution originale et efficace à un problème', 'PERSONNALITE', 2);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (257, 'Dans mes activités scolaires ou autres, je me montre méthodique et rationnel/le', 'PERSONNALITE', 2);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (258, 'J''aime la précision dans tout ce que je fais', 'PERSONNALITE', 2);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (259, 'Je demeure réservé/e dans l''expression de mes opinions, de mes sentiments et de mes actes', 'PERSONNALITE', 2);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (260, 'Avant toute décision, je réunis le maximum d''informations possible.', 'PERSONNALITE', 2);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (261, 'Mes amis me considèrent compliquée/e.', 'PERSONNALITE', 3);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (262, 'Dans mes diverses activités, je manque souvent d''ordre.', 'PERSONNALITE', 3);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (263, 'Dans mes travaux, je fais preuve d''originalité', 'PERSONNALITE', 3);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (264, 'Je suis d''un caractère impulsif.', 'PERSONNALITE', 3);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (265, 'Mes émotions sont généralement intenses.', 'PERSONNALITE', 3);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (266, 'Je suis porté/e à tout idéaliser et à chercher la perfection.', 'PERSONNALITE', 3);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (267, 'J''agis et je pense souvent de façon non conformiste, c''est-à-dire diffèremment des autres.', 'PERSONNALITE', 3);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (268, 'J''exprime mes sentiments par l''entremise de la musique, des beaux arts', 'PERSONNALITE', 3);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (269, 'Les lendemains ne m''inquiètent pas : je vis au jour le jour.', 'PERSONNALITE', 3);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (270, 'J''ai besoin de beaucoup de liberté dans tout ce que j''entreprends.', 'PERSONNALITE', 3);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (271, 'Quand un problème se pose, je préfère le régler par la discussion et l''entente avec les gens qui m''entourent', 'PERSONNALITE', 4);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (272, 'Je sais me montrer souple, conciliant/e.', 'PERSONNALITE', 4);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (273, 'Mes  amis/es me considèrent comme bienveillant/e et compréhensif/ve.', 'PERSONNALITE', 4);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (274, 'Généralement, les gens peuvent compter sur ma coopération.', 'PERSONNALITE', 4);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (275, 'Les gens me qualifient de sociale et sympathique.', 'PERSONNALITE', 4);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (276, 'Je suis d''un naturel serviable.', 'PERSONNALITE', 4);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (277, 'J''accepte et j''assume des responsabilités.', 'PERSONNALITE', 4);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (278, 'On me consièdère généreux/se.', 'PERSONNALITE', 4);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (279, 'Dans la majorité des circonstances, je suis perspicace', 'PERSONNALITE', 4);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (280, 'Dans l''action comme dans la façon de m''exprimer, je montre de la délicatesse.', 'PERSONNALITE', 4);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (281, '01. L''ambition ne m''effraye pas.', 'PERSONNALITE', 5);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (282, '02. Je suis un/e optimiste né/e.', 'PERSONNALITE', 5);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (283, '03. Je suis sociable et populaire ; je parle à tout le monde', 'PERSONNALITE', 5);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (284, '04. Je défends toujours mes opinions', 'PERSONNALITE', 5);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (285, '05. Il m''arrive souvent de me montrer autoritaire.', 'PERSONNALITE', 5);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (286, '06. L''aventure m''attire beaucoup.', 'PERSONNALITE', 5);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (287, '07. Généralement, je suis sûr/e de moi.', 'PERSONNALITE', 5);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (288, '08. Mes impulsions me dictent souvent ma conduite.', 'PERSONNALITE', 5);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (289, '09. J''aime être responsable d''activités.', 'PERSONNALITE', 5);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (290, '10. Même dans des situations critiques ou tendues, je sais prendre l''initiative nécessaire.', 'PERSONNALITE', 5);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (291, 'Je suis maître de moi, d''un calme exemplaire.', 'PERSONNALITE', 6);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (292, 'J''obéis facilement aux règlements et aux ordres.', 'PERSONNALITE', 6);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (293, 'Dans mes travaux, je suis persistant/e et consciencieux/se.', 'PERSONNALITE', 6);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (294, 'Je m''efforce de me montrer compétent/e dans ce qu''on exige de moi.', 'PERSONNALITE', 6);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (295, 'L''esprit concret et pratique me guide .', 'PERSONNALITE', 6);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (296, 'J''agis méthodiquement dans tout ce que je fais.', 'PERSONNALITE', 6);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (297, 'Je travaille avec beaucoup de soin.', 'PERSONNALITE', 6);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (298, 'D''une journée à l''autre, j''aime exécuter des tâches semblables.', 'PERSONNALITE', 6);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (299, 'Je suis timide et je préfère garder pour moi mes sentiments, mes émotions et mes idées.', 'PERSONNALITE', 6);
INSERT INTO `holland-back`.question (id, text, category, serial) VALUES (300, 'J''aime recevoir des instructions bien claires qui me permettent de savoir exactement ce qu''on attend de moi.', 'PERSONNALITE', 6);
